name: 'capstone_pipeline'
version: '1.0.0'
config-version: 2
profile: 'capstone_pipeline'
model-paths: ["models"]
clean-targets: ["target"]

models:
  capstone_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
